### ISSUE TITLE
NPE in [COMPLEX_EXPRESSION, REDUNDANT_SEMICOLON, WRONG_NEWLINES] rules

### ISSUE THREAD

**Issue by Cheshiriks** [cqfn/diKTat#1048] opened 2021-09-07 10:01 UTC
Examples:
`val testRootPath = saveProperties.testFiles!![0].toPath()`

**Comment by akuleshov7** [comment] 2021-09-07 11:34
duplicate of @kgevorkyan 's #1047

**Closed** 2021-09-22 12:05 UTC
Labels: bug, duplicate
